{% set name = "jaxonnxruntime" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxonnxruntime-{{ version }}.tar.gz
  sha256: 64340d83f280f725ef068326aedc87489a39f5da67ceebcdbcb24ce777cf8198

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - jax
    - jaxlib
    - numpy

test:
  imports:
    - jaxonnxruntime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jaxonnxruntime/
  summary: 'Jaxonnxruntime: JAX based ONNX Runtime.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
